# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: RethunkTech.Mortar
PackageVersion: 0.3.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: Rethunk.TechMortar
ReleaseDate: 2026-10-07
Protocols:
- mortar
- nxm
FileExtensions:
- mortar
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Rethunk-Tech/mortar/releases/download/v0.3.0/mortar-amd64-installer.exe
  InstallerSha256: 4279A68D312D60A431DAE8841B110E6A42EE6EF37EE0E9BF6A5BC93252516D7D
- Architecture: arm64
  InstallerUrl: https://github.com/Rethunk-Tech/mortar/releases/download/v0.3.0/mortar-arm64-installer.exe
  InstallerSha256: 3FF4024A6D30DB80E9934ECC8A0FFDA2AA81707BBC887A15D7B0EF1A637570BF
ManifestType: installer
ManifestVersion: 1.12.0
